# Generated by Django 4.0.2 on 2022-03-04 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.TextField(blank=True, null=True)),
                ('growth_rate', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IBIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naics_code', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('growth_rate_2021', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.TextField(blank=True, null=True)),
                ('product_basket', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True)),
                ('result_format', models.JSONField(blank=True, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 4, 15, 48, 26, 244304))),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor', models.TextField(blank=True, null=True)),
                ('relationship_basket', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SynergyMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('parent_company_or_financial_sponsor', models.TextField(blank=True, null=True)),
                ('hq_address', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('mission_statement', models.TextField(blank=True, null=True)),
                ('vision_statement', models.TextField(blank=True, null=True)),
                ('culture_and_values_keywords', models.TextField(blank=True, null=True)),
                ('corporate_culture', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('supply_chain_position', models.TextField(blank=True, null=True)),
                ('employees', models.TextField(blank=True, null=True)),
                ('key_employees', models.TextField(blank=True, null=True)),
                ('locations', models.TextField(blank=True, null=True)),
                ('hospitals', models.TextField(blank=True, null=True)),
                ('naics_six_digit_industry', models.TextField(blank=True, null=True)),
                ('industry_reference_code', models.TextField(blank=True, null=True)),
                ('industry_growth_rate', models.TextField(blank=True, null=True)),
                ('previous_year_igr', models.TextField(blank=True, null=True)),
                ('down_up_previous_year', models.TextField(blank=True, null=True)),
                ('down_up_five_year', models.TextField(blank=True, null=True)),
                ('specialty', models.TextField(blank=True, null=True)),
                ('speciality_growth_rate', models.TextField(blank=True, null=True)),
                ('speciality_interests', models.TextField(blank=True, null=True)),
                ('buyouts', models.TextField(blank=True, null=True)),
                ('attribute_interests', models.TextField(blank=True, null=True)),
                ('sector_focus', models.TextField(blank=True, null=True)),
                ('preferred_ebitda', models.TextField(blank=True, null=True)),
                ('preferred_revenue', models.TextField(blank=True, null=True)),
                ('preferred_ev', models.TextField(blank=True, null=True)),
                ('typical_equity_investments', models.TextField(blank=True, null=True)),
                ('cash_balance', models.TextField(blank=True, null=True)),
                ('profits', models.TextField(blank=True, null=True)),
                ('functional_descriptors', models.TextField(blank=True, null=True)),
                ('geographic_reach', models.TextField(blank=True, null=True)),
                ('us_geographic_reach', models.TextField(blank=True, null=True)),
                ('us_areas_of_expansion_left', models.TextField(blank=True, null=True)),
                ('areas_of_interest', models.TextField(blank=True, null=True)),
                ('products', models.TextField(blank=True, null=True)),
                ('target_consumer', models.TextField(blank=True, null=True)),
                ('primary_contact', models.TextField(blank=True, null=True)),
                ('industry_trends', models.TextField(blank=True, null=True)),
                ('consumer_demands_for_industry', models.TextField(blank=True, null=True)),
                ('mission_similarity', models.TextField(blank=True, null=True)),
                ('nlp_similiarity_of_descriptions', models.TextField(blank=True, null=True)),
                ('number_of_firms_in_industry', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('score', models.TextField(blank=True, null=True)),
                ('relationships', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_input', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_company_id', models.IntegerField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=100, null=True)),
                ('recommended_lead_notes', models.TextField(blank=True, null=True)),
                ('user_notes', models.TextField(blank=True, null=True)),
                ('is_recommended', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
