# Generated by Django 4.0.3 on 2022-03-09 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_question_updated'),
        ('api', '0002_synergymission_country_synergymission_state_and_more'),
    ]

    operations = [
    ]
