# Generated by Django 4.0.2 on 2022-03-14 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_synergymission_country_synergymission_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompany',
            name='programx_output',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 14, 10, 25, 30, 139191)),
        ),
    ]
