# Generated by Django 4.0.3 on 2022-03-15 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_merge_20220309_0646'),
        ('api', '0003_usercompany_programx_output_alter_question_updated'),
    ]

    operations = [
    ]
