# Generated by Django 4.0.2 on 2022-03-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlead',
            name='recommended_lead_notes',
        ),
        migrations.AddField(
            model_name='userlead',
            name='recommended_lead_note',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
