# Generated by Django 4.0.2 on 2022-05-11 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_contact_message_contact_name_contact_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='synergymission',
            old_name='corporate_culture',
            new_name='culture_and_values',
        ),
        migrations.RenameField(
            model_name='synergymission',
            old_name='culture_and_values_keywords',
            new_name='workplace_culture',
        ),
    ]
